// Generated by gencpp from file robot_pose_ekf_hdl/GetStatus.msg
// DO NOT EDIT!


#ifndef ROBOT_POSE_EKF_HDL_MESSAGE_GETSTATUS_H
#define ROBOT_POSE_EKF_HDL_MESSAGE_GETSTATUS_H

#include <ros/service_traits.h>


#include <robot_pose_ekf_hdl/GetStatusRequest.h>
#include <robot_pose_ekf_hdl/GetStatusResponse.h>


namespace robot_pose_ekf_hdl
{

struct GetStatus
{

typedef GetStatusRequest Request;
typedef GetStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStatus
} // namespace robot_pose_ekf_hdl


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_pose_ekf_hdl::GetStatus > {
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::robot_pose_ekf_hdl::GetStatus&) { return value(); }
};

template<>
struct DataType< ::robot_pose_ekf_hdl::GetStatus > {
  static const char* value()
  {
    return "robot_pose_ekf_hdl/GetStatus";
  }

  static const char* value(const ::robot_pose_ekf_hdl::GetStatus&) { return value(); }
};


// service_traits::MD5Sum< ::robot_pose_ekf_hdl::GetStatusRequest> should match
// service_traits::MD5Sum< ::robot_pose_ekf_hdl::GetStatus >
template<>
struct MD5Sum< ::robot_pose_ekf_hdl::GetStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_pose_ekf_hdl::GetStatus >::value();
  }
  static const char* value(const ::robot_pose_ekf_hdl::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_pose_ekf_hdl::GetStatusRequest> should match
// service_traits::DataType< ::robot_pose_ekf_hdl::GetStatus >
template<>
struct DataType< ::robot_pose_ekf_hdl::GetStatusRequest>
{
  static const char* value()
  {
    return DataType< ::robot_pose_ekf_hdl::GetStatus >::value();
  }
  static const char* value(const ::robot_pose_ekf_hdl::GetStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_pose_ekf_hdl::GetStatusResponse> should match
// service_traits::MD5Sum< ::robot_pose_ekf_hdl::GetStatus >
template<>
struct MD5Sum< ::robot_pose_ekf_hdl::GetStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_pose_ekf_hdl::GetStatus >::value();
  }
  static const char* value(const ::robot_pose_ekf_hdl::GetStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_pose_ekf_hdl::GetStatusResponse> should match
// service_traits::DataType< ::robot_pose_ekf_hdl::GetStatus >
template<>
struct DataType< ::robot_pose_ekf_hdl::GetStatusResponse>
{
  static const char* value()
  {
    return DataType< ::robot_pose_ekf_hdl::GetStatus >::value();
  }
  static const char* value(const ::robot_pose_ekf_hdl::GetStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_POSE_EKF_HDL_MESSAGE_GETSTATUS_H
